### ISSUE TITLE
Image Orientations 

### ISSUE THREAD

**Issue by kwahid** [brianmanderson/Dicom_RT_and_Images_to_Mask#3]
I’m currently working with T2 MRI sequences, and I’ve noticed for multiple patients if the images were acquired in non-standard image orientations, i.e. DICOM tag (0020, 0037) != [1\0\0\0\1\0], the contour masks don’t really match up with the images. This isn’t a huge problem for most data from big centers, but for some outside imaging this can be an issue. I’ve checked this for multiple patients now and it seems to be a recurring problem.

**Comment by brianmanderson** [comment]
Hey, great catch! The problem was that I wasn't taking into account the Xx, Xy, Xz, Yx, Yy, and Yz component of the tag that you've included.

This has been fixed now for Contours -> Mask b256c192a95ef34aa0b92884b702195a332a2bb1 and 1d69bf845345e4e0df13af24e56207c0feecd7aa
Unfortunately I'm having a hard time doing the opposite.. ensuring that masks created on Oblique images are properly turned into RT structures..I'll open a new issue ticket for it while I try to work it out

*Edit to include both commits

**Comment by brianmanderson** [comment]
Reference for what I used to understand what was going on*
http://dicomiseasy.blogspot.com/2013/06/getting-oriented-using-image-plane.html
